import type { AgentComponentId, AgentGroupId } from "./agent-types";

export const AGENT_OPEN_SOURCE_REVIEW_DATE = "2026-07-17";

export type AgentOpenSourceKind =
  | "Database"
  | "Framework"
  | "Gateway"
  | "Library"
  | "Platform"
  | "Protocol"
  | "Runtime"
  | "Standard";

export type AgentOpenSourceScope = "full-project" | "oss-core" | "specification";
export type AgentOpenSourceMaintenance = "active" | "stable-standard";

export interface AgentOpenSourceSolution {
  readonly name: string;
  readonly kind: AgentOpenSourceKind;
  readonly description: string;
  readonly languages: readonly string[];
  readonly license: string;
  readonly scope: AgentOpenSourceScope;
  readonly maintenance: AgentOpenSourceMaintenance;
  readonly releaseChannel: "stable";
  readonly reviewedOn: typeof AGENT_OPEN_SOURCE_REVIEW_DATE;
  readonly officialUrl: `https://${string}`;
}

export const agentOpenSourceCatalog = {
  "ag-ui": {
    name: "AG-UI",
    kind: "Protocol",
    description: "Standardizes event-driven communication between agent backends and interactive frontends.",
    languages: ["TypeScript", "Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.ag-ui.com/",
  },
  "ai-sdk": {
    name: "AI SDK",
    kind: "Library",
    description: "Builds streaming, tool-aware AI application interfaces with typed server and UI primitives.",
    languages: ["TypeScript"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://ai-sdk.dev/docs/introduction",
  },
  cedar: {
    name: "Cedar",
    kind: "Library",
    description: "Evaluates expressive authorization policies with a schema-backed policy language.",
    languages: ["Rust", "Java", "C++"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.cedarpolicy.com/",
  },
  cloudevents: {
    name: "CloudEvents",
    kind: "Standard",
    description: "Defines a stable, vendor-neutral event envelope across transports and services.",
    languages: ["Cross-language"],
    license: "Apache-2.0",
    scope: "specification",
    maintenance: "stable-standard",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://cloudevents.io/",
  },
  contextforge: {
    name: "ContextForge",
    kind: "Gateway",
    description: "Federates MCP servers and APIs behind centralized discovery, governance, and observability.",
    languages: ["Python", "Cross-language API"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://ibm.github.io/mcp-context-forge/latest/",
  },
  debezium: {
    name: "Debezium",
    kind: "Platform",
    description: "Streams source-of-record changes into event-driven data and indexing pipelines.",
    languages: ["Java", "Cross-language"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://debezium.io/documentation/reference/stable/",
  },
  docling: {
    name: "Docling",
    kind: "Library",
    description: "Parses complex documents into structured, ingestion-ready content for retrieval pipelines.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docling-project.github.io/docling/",
  },
  "envoy-gateway": {
    name: "Envoy Gateway",
    kind: "Gateway",
    description: "Provides a Kubernetes-native traffic boundary for routing, policy, resilience, and telemetry.",
    languages: ["Go", "Cross-language"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://gateway.envoyproxy.io/",
  },
  fastapi: {
    name: "FastAPI",
    kind: "Framework",
    description: "Exposes typed Python service and tool boundaries through OpenAPI-compatible APIs.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://fastapi.tiangolo.com/",
  },
  fastmcp: {
    name: "FastMCP",
    kind: "Framework",
    description: "Builds Python MCP servers, clients, and applications with typed schemas and managed protocol lifecycle.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://gofastmcp.com/getting-started/welcome",
  },
  "google-adk": {
    name: "Google Agent Development Kit",
    kind: "Framework",
    description: "Builds agent workflows with explicit tools, sessions, callbacks, and graph execution.",
    languages: ["Python", "TypeScript", "Go", "Java"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://adk.dev/",
  },
  gradio: {
    name: "Gradio",
    kind: "Framework",
    description: "Creates Python-first AI application and chat interfaces for prototypes and internal tools.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://www.gradio.app/guides/quickstart",
  },
  haystack: {
    name: "Haystack",
    kind: "Framework",
    description: "Composes production retrieval, document processing, ranking, and agent pipelines.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.haystack.deepset.ai/docs/intro",
  },
  keycloak: {
    name: "Keycloak",
    kind: "Platform",
    description: "Supplies workforce and workload identity through standard authentication protocols.",
    languages: ["Java", "Cross-language"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://www.keycloak.org/",
  },
  kserve: {
    name: "KServe",
    kind: "Platform",
    description: "Operates autoscaled model inference endpoints on Kubernetes with standardized serving APIs.",
    languages: ["Python", "Go", "Cross-language"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://kserve.github.io/website/latest/",
  },
  "langchain-mcp-adapters": {
    name: "LangChain MCP Adapters",
    kind: "Library",
    description: "Connects MCP tools, resources, and prompts to LangChain and LangGraph runtimes.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.langchain.com/oss/python/langchain/mcp",
  },
  langfuse: {
    name: "Langfuse OSS core",
    kind: "Platform",
    description: "Versions prompts and captures traces, scores, datasets, and experiments for LLM systems.",
    languages: ["TypeScript", "Python"],
    license: "MIT (OSS core)",
    scope: "oss-core",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://langfuse.com/docs",
  },
  langgraph: {
    name: "LangGraph",
    kind: "Runtime",
    description: "Implements stateful graph orchestration with persistence, interrupts, and durable execution.",
    languages: ["Python", "TypeScript"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.langchain.com/oss/python/langgraph/overview",
  },
  litellm: {
    name: "LiteLLM OSS core",
    kind: "Gateway",
    description: "Normalizes model provider APIs and centralizes routing, fallback, budgets, and usage telemetry.",
    languages: ["Python", "Cross-language API"],
    license: "MIT (OSS core)",
    scope: "oss-core",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.litellm.ai/",
  },
  "llama-index": {
    name: "LlamaIndex Workflows",
    kind: "Framework",
    description: "Builds event-driven, async-first workflows for document-centric and agent applications.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.llamaindex.ai/en/stable/",
  },
  mcp: {
    name: "MCP protocol + stable official SDK",
    kind: "Protocol",
    description: "Standardizes discovery and invocation of tools, resources, and prompts across agent hosts.",
    languages: ["Cross-language"],
    license: "Apache-2.0 / MIT transition",
    scope: "specification",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://modelcontextprotocol.io/docs/learn/architecture",
  },
  mlflow: {
    name: "MLflow",
    kind: "Platform",
    description: "Provides OpenTelemetry-compatible tracing, evaluation, prompt management, and experiments.",
    languages: ["Python", "TypeScript", "Java", "R"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://mlflow.org/docs/latest/genai/",
  },
  nats: {
    name: "NATS JetStream",
    kind: "Platform",
    description: "Carries durable messages and events with acknowledgements, replay, and stream retention.",
    languages: ["Cross-language"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.nats.io/nats-concepts/jetstream",
  },
  opa: {
    name: "Open Policy Agent",
    kind: "Platform",
    description: "Evaluates centralized policy-as-code decisions from explicit identity, resource, and run facts.",
    languages: ["Rego", "Cross-language API"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://www.openpolicyagent.org/docs",
  },
  opensearch: {
    name: "OpenSearch",
    kind: "Platform",
    description: "Provides lexical, vector, hybrid, and filtered search across governed corpora.",
    languages: ["Java", "Cross-language API"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.opensearch.org/latest/",
  },
  opentelemetry: {
    name: "OpenTelemetry",
    kind: "Standard",
    description: "Defines vendor-neutral traces, metrics, logs, context propagation, and collection pipelines.",
    languages: ["Cross-language"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://opentelemetry.io/docs/",
  },
  pgvector: {
    name: "PostgreSQL + pgvector",
    kind: "Database",
    description: "Keeps durable application records and vector retrieval in one transactional data boundary.",
    languages: ["SQL", "Cross-language"],
    license: "PostgreSQL License",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://github.com/pgvector/pgvector",
  },
  postgresql: {
    name: "PostgreSQL",
    kind: "Database",
    description: "Stores durable run, receipt, audit, and governed memory records transactionally.",
    languages: ["SQL", "Cross-language"],
    license: "PostgreSQL License",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://www.postgresql.org/docs/current/",
  },
  promptfoo: {
    name: "Promptfoo",
    kind: "Framework",
    description: "Runs repeatable prompt, model, red-team, and agent evaluations in CI and locally.",
    languages: ["TypeScript", "Python integrations"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://www.promptfoo.dev/docs/intro/",
  },
  pydantic: {
    name: "Pydantic",
    kind: "Library",
    description: "Validates typed Python request, state, tool, and result contracts at runtime.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.pydantic.dev/latest/",
  },
  "pydantic-ai": {
    name: "Pydantic AI",
    kind: "Framework",
    description: "Builds typed Python agents with validated dependencies, outputs, tools, and runtime integrations.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://pydantic.dev/docs/ai/",
  },
  qdrant: {
    name: "Qdrant",
    kind: "Database",
    description: "Provides a dedicated vector search service with filtering and collection isolation.",
    languages: ["Rust", "Cross-language API"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://qdrant.tech/documentation/",
  },
  ragas: {
    name: "Ragas by Vibrant Labs",
    kind: "Framework",
    description: "Evaluates RAG and agent systems with datasets, metrics, experiments, and testset generation.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.ragas.io/en/stable/",
  },
  temporal: {
    name: "Temporal",
    kind: "Runtime",
    description: "Executes failure-resilient workflows with durable timers, retries, signals, and recovery.",
    languages: ["Go", "Java", "Python", "TypeScript", ".NET", "PHP", "Ruby"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.temporal.io/",
  },
  trino: {
    name: "Trino",
    kind: "Platform",
    description: "Federates governed SQL queries across heterogeneous systems without copying every source.",
    languages: ["Java", "SQL", "Cross-language"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://trino.io/docs/current/",
  },
  vllm: {
    name: "vLLM",
    kind: "Runtime",
    description: "Serves open-weight language models with high-throughput, OpenAI-compatible inference APIs.",
    languages: ["Python", "Cross-language API"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.vllm.ai/en/stable/",
  },
  airflow: {
    name: "Apache Airflow",
    kind: "Platform",
    description: "Schedules observable batch workflows for offline ingestion, indexing, and evaluation pipelines.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://airflow.apache.org/docs/apache-airflow/stable/",
  },
  bentoml: {
    name: "BentoML",
    kind: "Platform",
    description: "Packages and serves Python model inference services with production deployment primitives.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.bentoml.com/en/latest/",
  },
  celery: {
    name: "Celery",
    kind: "Framework",
    description: "Runs distributed Python task queues with scheduling, acknowledgement, retry, and worker controls.",
    languages: ["Python"],
    license: "BSD-3-Clause",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.celeryq.dev/en/stable/",
  },
  crewai: {
    name: "CrewAI",
    kind: "Framework",
    description: "Coordinates role-oriented Python agents and explicit flows for collaborative task execution.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.crewai.com/",
  },
  dbos: {
    name: "DBOS",
    kind: "Runtime",
    description: "Executes durable Python workflows, queues, timers, and recovery with state persisted in PostgreSQL.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.dbos.dev/python/tutorials/workflow-tutorial",
  },
  deepeval: {
    name: "DeepEval",
    kind: "Framework",
    description: "Tests LLM and agent behavior with reusable metrics, datasets, and CI-oriented evaluation runs.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://deepeval.com/docs/introduction",
  },
  dspy: {
    name: "DSPy",
    kind: "Framework",
    description: "Programs and optimizes modular language-model pipelines against measurable objectives.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://dspy.ai/",
  },
  instructor: {
    name: "Instructor",
    kind: "Library",
    description: "Extracts and retries validated structured model outputs through Python type schemas.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://python.useinstructor.com/",
  },
  langchain: {
    name: "LangChain",
    kind: "Framework",
    description: "Provides Python integrations and composable primitives for models, tools, retrieval, and agents.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.langchain.com/oss/python/langchain/overview",
  },
  mem0: {
    name: "Mem0 OSS",
    kind: "Library",
    description: "Adds an application-managed memory layer for extracting, updating, and retrieving agent memories.",
    languages: ["Python", "TypeScript"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.mem0.ai/open-source/overview",
  },
  "nats-py": {
    name: "nats.py",
    kind: "Library",
    description: "Connects Python services to NATS and JetStream for messaging, persistence, and request-reply.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://github.com/nats-io/nats.py",
  },
  "opentelemetry-python": {
    name: "OpenTelemetry Python",
    kind: "Library",
    description: "Instruments stable Python traces and metrics; the Python logs signal remains in development.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://opentelemetry.io/docs/languages/python/",
  },
  "pgvector-python": {
    name: "pgvector-python",
    kind: "Library",
    description: "Adds pgvector types and vector operations to popular Python PostgreSQL and ORM clients.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://github.com/pgvector/pgvector-python",
  },
  prefect: {
    name: "Prefect",
    kind: "Platform",
    description: "Orchestrates observable Python workflows with retries, scheduling, state, and human interaction.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.prefect.io/v3/",
  },
  psycopg: {
    name: "Psycopg",
    kind: "Library",
    description: "Provides a modern PostgreSQL adapter with async, pooling, and typed data support for Python.",
    languages: ["Python"],
    license: "LGPL-3.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://www.psycopg.org/psycopg3/docs/",
  },
  pycasbin: {
    name: "PyCasbin",
    kind: "Library",
    description: "Enforces deterministic authorization models directly inside Python services.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://github.com/apache/casbin-pycasbin",
  },
  "ray-serve": {
    name: "Ray Serve",
    kind: "Runtime",
    description: "Composes and scales online Python inference services across distributed Ray clusters.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.ray.io/en/latest/serve/",
  },
  smolagents: {
    name: "smolagents",
    kind: "Framework",
    description: "Builds compact Python agents with code or tool execution and broad model integrations.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://huggingface.co/docs/smolagents/index",
  },
  sqlalchemy: {
    name: "SQLAlchemy",
    kind: "Library",
    description: "Provides explicit Python SQL, transaction, connection, and object-relational persistence primitives.",
    languages: ["Python"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.sqlalchemy.org/en/20/",
  },
  streamlit: {
    name: "Streamlit",
    kind: "Framework",
    description: "Builds Python-first data and AI applications for internal operators and rapid product validation.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://docs.streamlit.io/",
  },
  "trino-python": {
    name: "Trino Python client",
    kind: "Library",
    description: "Runs governed Trino queries from Python through DB-API and SQLAlchemy integrations.",
    languages: ["Python"],
    license: "Apache-2.0",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://github.com/trinodb/trino-python-client",
  },
  zod: {
    name: "Zod",
    kind: "Library",
    description: "Validates TypeScript request, tool, and response schemas at runtime.",
    languages: ["TypeScript"],
    license: "MIT",
    scope: "full-project",
    maintenance: "active",
    releaseChannel: "stable",
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    officialUrl: "https://zod.dev/",
  },
} as const satisfies Readonly<Record<string, AgentOpenSourceSolution>>;

export type AgentOpenSourceSolutionId = keyof typeof agentOpenSourceCatalog;

export interface AgentOpenSourceChoice {
  readonly solutionId: AgentOpenSourceSolutionId;
  readonly useFor: string;
}

export interface AgentSolutionTrack {
  readonly preferred: AgentOpenSourceChoice;
  readonly companions: readonly AgentOpenSourceChoice[];
  readonly alternatives: readonly AgentOpenSourceChoice[];
  readonly decisionRule: string;
}

export interface AgentOpenSourceRecommendation extends AgentSolutionTrack {
  readonly reviewedOn: typeof AGENT_OPEN_SOURCE_REVIEW_DATE;
  readonly pythonEcosystem: AgentSolutionTrack;
  readonly architectureExceptionReason?: string;
}

function choice(
  solutionId: AgentOpenSourceSolutionId,
  useFor: string,
): AgentOpenSourceChoice {
  return { solutionId, useFor };
}

function track(
  preferred: AgentOpenSourceChoice,
  companions: readonly AgentOpenSourceChoice[],
  alternatives: readonly AgentOpenSourceChoice[],
  decisionRule: string,
): AgentSolutionTrack {
  return {
    preferred,
    companions,
    alternatives,
    decisionRule,
  };
}

const agentGroupArchitectureRecommendations = {
  entry: track(
    choice("envoy-gateway", "Enforce routing, timeouts, rate limits, and telemetry at the platform edge."),
    [
      choice("keycloak", "Issue and verify human or workload identity before admission."),
      choice("cloudevents", "Normalize asynchronous request metadata across transports."),
    ],
    [choice("nats", "Use when durable event admission and replay are central requirements.")],
    "Keep transport, identity, and task validation separate: the gateway admits traffic, the identity provider establishes the caller, and the runtime receives one typed envelope.",
  ),
  runtime: track(
    choice("langgraph", "Implement the explicit agent state graph, checkpoints, interrupts, and bounded run loop."),
    [choice("temporal", "Add durable cross-service execution when work must survive process or infrastructure failure.")],
    [
      choice("pydantic-ai", "Choose for a Python-first typed agent runtime with an integrated FastMCP-backed MCP client."),
      choice("google-adk", "Choose for a broader multi-language agent framework with built-in sessions and graph workflows."),
    ],
    "Use LangGraph for agent-state orchestration; introduce Temporal when the run crosses services, lasts a long time, or needs stronger operational durability.",
  ),
  context: track(
    choice("langgraph", "Own short-lived run state and reproducible context assembly around each graph step."),
    [
      choice("pgvector", "Persist governed memory and vector-searchable records transactionally."),
      choice("langfuse", "Version prompt and instruction assets with traceable usage."),
    ],
    [choice("qdrant", "Choose when vector search needs an independently scaled service.")],
    "Separate working state, durable memory, and prompt assets. Do not turn a vector store into the source of truth for the complete run.",
  ),
  models: track(
    choice("litellm", "Expose one governed model API with routing, budgets, fallbacks, and usage accounting."),
    [
      choice("vllm", "Serve private or open-weight models behind the same gateway contract."),
      choice("kserve", "Operate autoscaled inference endpoints when Kubernetes is the serving control plane."),
    ],
    [],
    "Keep model routing outside the agent graph. Route by evaluated capability, data boundary, latency, and cost while preserving one typed result contract.",
  ),
  agents: track(
    choice("langgraph", "Represent coordinator and worker delegation as explicit subgraphs or bounded tasks."),
    [],
    [
      choice("google-adk", "Choose for multi-language teams that want a batteries-included agent framework."),
      choice("llama-index", "Choose for Python, document-centric, event-driven agent workflows."),
    ],
    "Prefer explicit graphs and typed worker results over free-form agent chat. Select one orchestration framework as the owner of run state.",
  ),
  tools: track(
    choice("mcp", "Standardize external capability discovery while keeping tools, resources, and prompts distinct."),
    [
      choice("fastmcp", "Use as the preferred Python implementation for MCP servers, clients, and applications."),
      choice("langchain-mcp-adapters", "Load MCP tools, resources, and prompts into the selected LangGraph runtime."),
      choice("contextforge", "Federate and govern MCP servers at the shared platform gateway and registry boundary."),
    ],
    [choice("pydantic-ai", "Choose only when Pydantic AI replaces LangGraph as the agent runtime and owns MCP client lifecycle.")],
    "Use MCP as the portable contract, FastMCP as the preferred Python implementation, LangChain MCP Adapters as the LangGraph bridge, and ContextForge only at the shared gateway. Use Pydantic AI's MCP client instead of the LangGraph adapter only when Pydantic AI owns the runtime. Keep every dependency on its current stable release.",
  ),
  governance: track(
    choice("opa", "Make deterministic admission, data, tool, and action decisions from explicit facts."),
    [
      choice("promptfoo", "Run repeatable safety, behavior, and regression evaluations before release."),
      choice("mlflow", "Track evaluation evidence, datasets, prompts, and production quality signals."),
    ],
    [choice("cedar", "Choose when schema-backed application authorization is the main policy problem.")],
    "Keep authorization deterministic and versioned. Treat model-based evaluation as evidence, not as the authority that grants access or permits writes.",
  ),
  outcome: track(
    choice("opentelemetry", "Emit vendor-neutral traces, metrics, logs, and correlation context for every run branch."),
    [choice("nats", "Deliver durable asynchronous outcomes and independent branch receipts.")],
    [
      choice("mlflow", "Choose for an integrated AI engineering, evaluation, and observability platform."),
      choice("langfuse", "Choose for an LLM-focused prompt, trace, dataset, and score workflow."),
    ],
    "Instrument with OpenTelemetry first, then select an analysis backend. Delivery, memory write, and telemetry must report success independently.",
  ),
} satisfies Readonly<Record<AgentGroupId, AgentSolutionTrack>>;

const agentComponentArchitectureRecommendations = {
  "user-application": track(
    choice("ai-sdk", "Build a typed, streaming application boundary for chat, tools, and structured results."),
    [
      choice("ag-ui", "Standardize event exchange when the frontend and agent runtime are separate systems."),
      choice("zod", "Validate TypeScript request, tool, and response contracts at the application boundary."),
    ],
    [choice("gradio", "Choose for Python-first prototypes and internal operator interfaces.")],
    "Use AI SDK for a product-grade TypeScript interface, AG-UI for backend-neutral interoperability, or Gradio when a Python team needs a fast internal UI.",
  ),
  "event-message": track(
    choice("nats", "Provide durable admission, acknowledgement, retry, replay, and dead-letter handling."),
    [choice("cloudevents", "Give events a stable envelope independent of the transport.")],
    [choice("temporal", "Choose when each message begins a long-running, stateful business workflow.")],
    "Use a broker for delivery semantics and CloudEvents for envelope portability; acknowledge only after the run is durably admitted.",
  ),
  "input-gateway": track(
    choice("envoy-gateway", "Enforce edge routing, quotas, request limits, resilience, and observability."),
    [choice("keycloak", "Authenticate users and workloads and propagate scoped identity claims.")],
    [choice("fastapi", "Choose for an application-owned Python gateway with custom typed admission logic.")],
    "Keep coarse traffic controls at the edge and semantic TaskContract validation in application code. Never let the model repair identity or authority failures.",
  ),
  coordinator: track(
    choice("langgraph", "Implement the observe-decide-dispatch-evaluate loop as explicit durable graph state."),
    [],
    [
      choice("google-adk", "Choose for multi-language sessions and graph workflows in one agent framework."),
      choice("llama-index", "Choose for Python event-driven workflows with document-heavy steps."),
    ],
    "Select one coordinator that owns run state, budgets, and exits. Models may propose the next step but must not own retries, persistence, or authorization.",
  ),
  "task-scheduler": track(
    choice("temporal", "Own durable task state, dependencies, leases, timers, retry policy, and cancellation."),
    [choice("nats", "Carry ready-task notifications when workers are independently deployed.")],
    [choice("langgraph", "Choose when scheduling stays inside one agent graph and process boundary.")],
    "Use Temporal for cross-service or long-running work; use graph-native scheduling only when the complete lifecycle can remain inside the agent runtime.",
  ),
  "working-context": track(
    choice("langgraph", "Checkpoint typed per-run state and expose only the state required by the next node."),
    [choice("pydantic", "Validate Python context records and state transitions at runtime.")],
    [choice("llama-index", "Choose for event-typed Python workflow context and step-local state.")],
    "Treat working context as explicit state, not accumulated chat text. Persist decisions, ownership, evidence references, and open work before compaction.",
  ),
  "long-term-memory": track(
    choice("pgvector", "Store governed memory records and embeddings beside transactional metadata and provenance."),
    [],
    [
      choice("qdrant", "Choose when vector retrieval needs independent scale and collection isolation."),
      choice("opensearch", "Choose when hybrid lexical-vector discovery is more important than transactional co-location."),
    ],
    "Start with PostgreSQL plus pgvector when memory is application data. Move vector search to a dedicated service only when scale or search behavior justifies another source boundary.",
  ),
  "skills-instructions": track(
    choice("langfuse", "Version prompts and instruction assets and link every use to a trace and evaluation."),
    [choice("promptfoo", "Regression-test prompt and instruction changes before promotion.")],
    [choice("mlflow", "Choose when prompt management must share one platform with experiments and model evaluation.")],
    "Store instructions as versioned artifacts with owners and evaluation evidence; do not edit production prompts without a traceable promotion path.",
  ),
  "context-manager": track(
    choice("langgraph", "Assemble reproducible context from graph state, stores, and explicit node inputs."),
    [],
    [
      choice("haystack", "Choose when retrieval pipelines dominate context assembly."),
      choice("llama-index", "Choose for Python event-driven context flows around document agents."),
    ],
    "Choose an orchestrator for authority and ordering, then call retrieval as a bounded dependency. Retrieved relevance must never override instruction authority.",
  ),
  "general-model": track(
    choice("litellm", "Normalize general-model calls, routing, fallback, budgets, and usage behind one API."),
    [choice("pydantic", "Validate Python structured outputs before accepting them into run state.")],
    [choice("ai-sdk", "Choose for TypeScript structured generation and tool-call integration.")],
    "Keep the model stateless and replaceable. Validate every structured result in application code and preserve the endpoint identity for evaluation.",
  ),
  "private-model": track(
    choice("vllm", "Serve open-weight models efficiently behind an OpenAI-compatible endpoint."),
    [
      choice("kserve", "Add Kubernetes-native autoscaling, rollout, and inference lifecycle management."),
      choice("litellm", "Expose private and hosted endpoints through the same governed model contract."),
    ],
    [],
    "Use vLLM for the inference engine, KServe for fleet operations, and LiteLLM for policy-aware routing. Never let fallback cross the approved data boundary.",
  ),
  "worker-a": track(
    choice("haystack", "Compose read-only search, retrieval, ranking, and evidence-bundle pipelines."),
    [],
    [
      choice("llama-index", "Choose for event-driven, document-centric research workflows."),
      choice("opensearch", "Choose when the worker mainly queries an existing hybrid search platform."),
    ],
    "Give the research worker read-only tools and require source locators, freshness, and unresolved gaps in its typed return.",
  ),
  "worker-b": track(
    choice("langgraph", "Model analysis, evidence checks, revision, and escalation as inspectable graph nodes."),
    [choice("pydantic", "Validate structured comparison and decision outputs in Python.")],
    [choice("google-adk", "Choose when analysis workers share an ADK-based multi-language agent platform.")],
    "Separate evidence sufficiency from synthesis. Return a typed NeedsEvidence result instead of manufacturing certainty when inputs are incomplete.",
  ),
  "worker-c": track(
    choice("temporal", "Execute approved writes with durable attempts, retries, compensation, and postcondition checks."),
    [choice("opa", "Authorize the exact operation, target, arguments, actor, and expiry before dispatch.")],
    [choice("mcp", "Choose a stable official SDK when the action capability is exposed by an MCP server.")],
    "Use durable workflow code for side effects and reconcile external state before retrying an uncertain outcome. Approval is narrow and single-use.",
  ),
  "function-tool": track(
    choice("fastmcp", "Build the preferred Python MCP server and client boundary with generated schemas and managed lifecycle."),
    [
      choice("mcp", "Keep tools, resources, and prompts portable through the language-neutral protocol contract."),
      choice("langchain-mcp-adapters", "Expose approved MCP capabilities to the LangGraph runtime and its tool interceptors."),
      choice("pydantic", "Validate Python tool arguments and results."),
    ],
    [
      choice("pydantic-ai", "Choose when Pydantic AI, rather than LangGraph, owns the agent runtime and MCP client lifecycle."),
      choice("fastapi", "Choose for an internal HTTP tool service with an application-owned API contract."),
    ],
    "Use FastMCP for Python MCP implementation and LangChain MCP Adapters for the selected LangGraph runtime. Keep Pydantic AI's MCP client conditional on replacing that runtime. Protocol discovery and gateway federation never replace allowlisting, authorization, timeouts, idempotency, or result validation.",
  ),
  "retrieval-tool": track(
    choice("haystack", "Compose query rewrite, routing, hybrid retrieval, filtering, ranking, and evidence output."),
    [choice("docling", "Parse complex source documents into structured, ingestion-ready content for offline indexing.")],
    [
      choice("llama-index", "Choose for retrieval embedded in Python document workflows."),
      choice("opensearch", "Choose when retrieval logic can live close to an existing hybrid index."),
    ],
    "Return ranked evidence with provenance and source failures, never an unattributed answer. Evaluate ingestion quality separately from online retrieval quality.",
  ),
  "data-source": track(
    choice("trino", "Federate governed read queries across heterogeneous operational and analytical systems."),
    [
      choice("debezium", "Stream source changes into indexes, caches, and event consumers."),
      choice("postgresql", "Provide a transactional source of record for platform-owned data."),
    ],
    [],
    "Choose direct governed queries for current truth and CDC for derived indexes. Preserve source ACLs, consistency, timestamps, and lineage in every return.",
  ),
  "action-tool": track(
    choice("temporal", "Run idempotent writes, timers, retries, compensation, and state reconciliation durably."),
    [
      choice("opa", "Authorize exact write scope from deterministic policy facts."),
      choice("mcp", "Standardize capability invocation when an approved MCP server owns the action."),
    ],
    [],
    "Separate proposal, authority, execution, and verification. A timeout is an uncertain state that must be read back before any retry.",
  ),
  "policy-guard": track(
    choice("opa", "Evaluate centralized policy-as-code at every admission, data, tool, and action boundary."),
    [choice("keycloak", "Supply authenticated subject, tenant, role, and workload claims to policy decisions.")],
    [choice("cedar", "Choose for schema-backed application authorization with a compact policy model.")],
    "Use deterministic policy for authorization and store the policy version, inputs, reason code, constraints, and expiry with each decision.",
  ),
  "output-evaluator": track(
    choice("ragas", "Evaluate RAG and agent outputs against datasets and task-specific metrics."),
    [],
    [
      choice("promptfoo", "Choose for CI-focused regression, model comparison, and red-team suites."),
      choice("mlflow", "Choose for integrated datasets, experiments, scorers, tracing, and production monitoring."),
    ],
    "Run schema and evidence checks before model judges. Calibrate false accepts and false rejects by task class and preserve an uncertain outcome.",
  ),
  "human-approval": track(
    choice("temporal", "Pause durable workflows for human signals without losing timers, state, or cancellation."),
    [choice("opa", "Define which operations require approval and validate the approved scope on resume.")],
    [choice("langgraph", "Choose when the approval interrupt remains inside one agent graph lifecycle.")],
    "Use Temporal for long-lived or cross-service approvals and LangGraph interrupts for graph-local review. Bind approval to exact arguments, evidence, actor, and expiry.",
  ),
  "response-publisher": track(
    choice("nats", "Publish durable asynchronous outcomes with independent delivery attempts and receipts."),
    [choice("cloudevents", "Keep the accepted outcome envelope portable across delivery transports.")],
    [choice("ai-sdk", "Choose for interactive TypeScript streaming to a web application.")],
    "Separate accepted content identity from delivery-attempt identity so retries never regenerate or silently alter an already verified result.",
  ),
  "memory-writer": track(
    choice("postgresql", "Persist verified memory, provenance, ACL, retention, supersession, and audit data transactionally."),
    [choice("opa", "Evaluate retention and access policy before each write or read.")],
    [choice("qdrant", "Choose as a derived vector index, not as the only source of governed memory truth.")],
    "Write an explicit verified memory candidate, not raw run history. Keep the authoritative record transactional and treat search indexes as rebuildable projections.",
  ),
  "trace-telemetry": track(
    choice("opentelemetry", "Instrument traces, metrics, logs, baggage, and collector pipelines without backend lock-in."),
    [],
    [
      choice("mlflow", "Choose for integrated AI traces, evaluation, prompts, and production monitoring."),
      choice("langfuse", "Choose for an LLM-focused trace, prompt, score, and dataset workflow."),
    ],
    "Emit OpenTelemetry at the source and select a backend separately. Redact payloads before export and correlate run, task, attempt, model, tool, and policy IDs.",
  ),
} satisfies Readonly<Record<AgentComponentId, AgentSolutionTrack>>;

const agentGroupPythonEcosystem = {
  entry: track(
    choice("fastapi", "Implement typed Python admission APIs, validation hooks, and streaming endpoints."),
    [
      choice("gradio", "Give engineers a fast Python chat and tool-testing surface."),
      choice("streamlit", "Build richer internal operator workflows and data-oriented controls."),
    ],
    [choice("nats-py", "Use when Python services admit work primarily through durable NATS messages.")],
    "Start with FastAPI for a service boundary. Add Gradio for experiments or Streamlit for operator applications; use nats.py beside the API when durable asynchronous admission is required.",
  ),
  runtime: track(
    choice("langgraph", "Own typed agent state, checkpoints, interrupts, and graph execution in Python."),
    [
      choice("dbos", "Add durable Python workflows, queues, and recovery backed by PostgreSQL."),
      choice("pydantic-ai", "Use typed agents and dependencies for smaller runtime-owned workflows."),
    ],
    [
      choice("prefect", "Choose for observable Python workflow orchestration beyond the agent graph."),
      choice("google-adk", "Choose when ADK sessions and multi-agent graph primitives should own the runtime."),
    ],
    "Keep one owner for agent state. Pair LangGraph with DBOS when Python durability is needed; choose Prefect for general workflow operations or Pydantic AI for a smaller typed runtime.",
  ),
  context: track(
    choice("langgraph", "Assemble and checkpoint explicit per-run context at graph boundaries."),
    [
      choice("llama-index", "Build event-driven document context and retrieval workflows."),
      choice("pgvector-python", "Connect Python context services to governed vector records in PostgreSQL."),
    ],
    [
      choice("haystack", "Choose when retrieval pipelines dominate context construction."),
      choice("mem0", "Choose when the product needs a dedicated memory extraction and update layer."),
    ],
    "Use LangGraph for authoritative working state, LlamaIndex or Haystack for bounded retrieval assembly, and pgvector-python for storage access. Treat Mem0 as a managed memory layer, not run state.",
  ),
  models: track(
    choice("litellm", "Expose one Python model gateway for routing, budgets, fallbacks, and accounting."),
    [
      choice("instructor", "Validate and retry structured Python model outputs."),
      choice("vllm", "Serve private or open-weight models behind the same contract."),
    ],
    [
      choice("bentoml", "Choose for Python packaging and deployment of model services."),
      choice("ray-serve", "Choose for distributed multi-stage inference on a Ray cluster."),
    ],
    "Use LiteLLM as the provider boundary and Instructor at structured-output call sites. Add vLLM for inference; select BentoML or Ray Serve only when their deployment model matches platform operations.",
  ),
  agents: track(
    choice("langgraph", "Implement coordinator and worker graphs with explicit state and bounded delegation."),
    [
      choice("pydantic-ai", "Build typed specialist agents with validated dependencies and outputs."),
      choice("google-adk", "Integrate ADK agents when its sessions and tool lifecycle are platform requirements."),
    ],
    [
      choice("crewai", "Choose for role-oriented agent collaboration and explicit flows."),
      choice("llama-index", "Choose for document-centric, event-driven agent workflows."),
      choice("smolagents", "Choose for compact code- or tool-executing specialist agents."),
    ],
    "Default to LangGraph when platform engineers need inspectable control. Use Pydantic AI for typed specialists; choose CrewAI, LlamaIndex Workflows, or smolagents only for their specific collaboration or execution model.",
  ),
  tools: track(
    choice("fastmcp", "Build Python MCP servers, clients, and applications with typed capability schemas."),
    [
      choice("langchain-mcp-adapters", "Load MCP tools, resources, and prompts into LangGraph."),
      choice("contextforge", "Centralize MCP discovery, federation, authentication, policy, and telemetry."),
      choice("pydantic", "Validate tool inputs, outputs, and internal capability contracts."),
    ],
    [
      choice("pydantic-ai", "Choose when Pydantic AI owns the runtime and its MCP client lifecycle."),
      choice("fastapi", "Choose for internal HTTP tools that do not need MCP discovery semantics."),
    ],
    "Use FastMCP for Python MCP implementation, LangChain MCP Adapters for LangGraph integration, and ContextForge only at the shared gateway. Keep ordinary validation in Pydantic.",
  ),
  governance: track(
    choice("pycasbin", "Enforce deterministic authorization models inside Python service boundaries."),
    [
      choice("ragas", "Evaluate RAG and agent quality with Python datasets and metrics."),
      choice("deepeval", "Run reusable LLM and agent tests locally and in CI."),
    ],
    [
      choice("mlflow", "Choose when evaluation evidence belongs in a broader AI engineering platform."),
      choice("dspy", "Choose when prompt and module optimization is driven by measurable objectives."),
    ],
    "Keep PyCasbin decisions deterministic and independent from model judges. Use Ragas or DeepEval for quality evidence; add MLflow for lifecycle management or DSPy for systematic program optimization.",
  ),
  outcome: track(
    choice("opentelemetry-python", "Emit stable Python traces and metrics with portable context propagation."),
    [
      choice("nats-py", "Publish durable asynchronous outcomes and delivery receipts."),
      choice("sqlalchemy", "Persist accepted outcomes and branch receipts transactionally."),
      choice("mlflow", "Analyze AI traces, evaluation evidence, and production quality signals."),
    ],
    [choice("langfuse", "Choose for an LLM-focused trace, prompt, score, and dataset workflow.")],
    "Instrument Python code with OpenTelemetry, then keep delivery and persistence independent through nats.py and SQLAlchemy. Select MLflow or Langfuse as the analysis backend, not the source instrumentation contract.",
  ),
} satisfies Readonly<Record<AgentGroupId, AgentSolutionTrack>>;

const agentComponentPythonEcosystem = {
  "user-application": track(
    choice("streamlit", "Build an internal Python application with chat, state, data views, and operator controls."),
    [
      choice("gradio", "Use for rapid model, agent, and tool demonstrations."),
      choice("fastapi", "Expose the application-facing typed and streaming service API."),
    ],
    [choice("ag-ui", "Choose when a separate frontend needs a backend-neutral agent event protocol.")],
    "Use Streamlit for a Python-owned operator product, Gradio for fast experiments, and FastAPI as the durable service boundary. Add AG-UI only when frontend interoperability is required.",
  ),
  "event-message": track(
    choice("nats-py", "Publish, consume, acknowledge, replay, and request-reply through NATS from Python."),
    [choice("pydantic", "Validate the event envelope and payload before admission or acknowledgement.")],
    [choice("celery", "Choose when the platform already standardizes Python background work on Celery.")],
    "Prefer nats.py when messages cross independently deployed services. Use Celery for Python task queues, and validate either transport contract with Pydantic.",
  ),
  "input-gateway": track(
    choice("fastapi", "Implement typed request admission, authentication hooks, quotas, and streaming responses."),
    [choice("pydantic", "Validate TaskContract identity, authority, budget, and payload fields.")],
    [choice("nats-py", "Choose when admission begins on an asynchronous NATS subject instead of HTTP.")],
    "Put semantic admission in FastAPI and Pydantic. Use nats.py for an event-native boundary, while keeping the same validated TaskContract.",
  ),
  coordinator: track(
    choice("langgraph", "Own the observe-decide-dispatch-evaluate loop as explicit Python graph state."),
    [
      choice("pydantic-ai", "Implement typed specialist agents and validated coordinator dependencies."),
      choice("google-adk", "Use ADK agents when its sessions and callbacks are already the platform standard."),
    ],
    [
      choice("crewai", "Choose for role-oriented teams and flow-based collaboration."),
      choice("llama-index", "Choose for document-heavy event workflows."),
      choice("smolagents", "Choose for compact code- or tool-executing coordinators."),
    ],
    "Select exactly one coordinator to own state, budgets, retries, and exits. LangGraph is the default for explicit control; alternatives are bounded to their distinct programming models.",
  ),
  "task-scheduler": track(
    choice("dbos", "Run durable Python tasks, queues, timers, and recovery with PostgreSQL-backed state."),
    [choice("prefect", "Add scheduling, deployment, observability, and general workflow operations.")],
    [
      choice("celery", "Choose for conventional distributed Python task queues."),
      choice("langgraph", "Choose when scheduling remains inside one agent graph lifecycle."),
    ],
    "Use DBOS for code-level Python durability, Prefect for an operational workflow control plane, Celery for established queues, and LangGraph only for graph-local scheduling.",
  ),
  "working-context": track(
    choice("langgraph", "Checkpoint typed working state and expose only each node's required context."),
    [choice("pydantic", "Validate context records, transitions, and compaction summaries.")],
    [
      choice("llama-index", "Choose for event-typed document workflow context."),
      choice("mem0", "Choose for extracted user or agent memories outside authoritative run state."),
    ],
    "Keep authoritative working context in LangGraph and validate it with Pydantic. Use LlamaIndex for document events or Mem0 for a separate memory concern.",
  ),
  "long-term-memory": track(
    choice("pgvector-python", "Store and query governed vector records through Python PostgreSQL clients."),
    [
      choice("sqlalchemy", "Model authoritative memory records, transactions, and lifecycle metadata."),
      choice("psycopg", "Use direct async PostgreSQL access, pooling, and vector adapters."),
    ],
    [choice("mem0", "Choose when memory extraction, deduplication, and updates need a dedicated layer.")],
    "Use SQLAlchemy or Psycopg for the source record and pgvector-python for vector types. Add Mem0 only as an application memory layer over governed storage.",
  ),
  "skills-instructions": track(
    choice("langfuse", "Version prompt and instruction assets and link every use to traces and evaluations."),
    [choice("mlflow", "Track prompt versions beside experiments, traces, datasets, and scorers.")],
    [
      choice("dspy", "Choose when instructions are compiled and optimized against metrics."),
      choice("deepeval", "Choose for Python regression suites guarding instruction changes."),
    ],
    "Use Langfuse or MLflow as the governed artifact system. DSPy optimizes programs and DeepEval tests them; neither replaces ownership and promotion controls.",
  ),
  "context-manager": track(
    choice("langgraph", "Order context assembly and preserve authority through explicit graph nodes."),
    [
      choice("haystack", "Compose retrieval, filtering, ranking, and evidence pipelines."),
      choice("llama-index", "Compose document-aware event workflows and indexes."),
    ],
    [
      choice("langchain", "Choose for its broader Python integration and runnable ecosystem."),
      choice("mem0", "Choose when user or agent memory is a first-class context input."),
    ],
    "Let LangGraph own ordering and authority. Call Haystack or LlamaIndex as bounded retrieval dependencies; use LangChain for integration breadth or Mem0 for explicit memory input.",
  ),
  "general-model": track(
    choice("litellm", "Normalize Python model calls, routing, fallback, budgets, and usage."),
    [
      choice("pydantic", "Validate model results before accepting them into run state."),
      choice("instructor", "Retry structured extraction against typed Python schemas."),
    ],
    [
      choice("langchain", "Choose for provider integrations embedded in LangChain runnables."),
      choice("pydantic-ai", "Choose when typed agents own model invocation and result validation."),
    ],
    "Keep LiteLLM as the replaceable provider boundary. Use Pydantic for contracts and Instructor for extraction retries; do not add a second model owner without a clear runtime decision.",
  ),
  "private-model": track(
    choice("vllm", "Serve private or open-weight models through a high-throughput compatible API."),
    [
      choice("bentoml", "Package and deploy Python inference services."),
      choice("ray-serve", "Scale distributed or multi-stage inference deployments."),
    ],
    [choice("kserve", "Choose when Kubernetes-native inference lifecycle is the platform standard.")],
    "Use vLLM for the inference engine. Add BentoML, Ray Serve, or KServe as the operational serving layer according to packaging, cluster, and Kubernetes requirements.",
  ),
  "worker-a": track(
    choice("haystack", "Build read-only retrieval, ranking, and evidence-bundle pipelines."),
    [
      choice("llama-index", "Add event-driven document workflows and index integrations."),
      choice("langchain", "Use its Python loader and integration breadth around retrieval."),
    ],
    [
      choice("smolagents", "Choose for a compact tool-using research agent."),
      choice("crewai", "Choose when research is split across explicit agent roles."),
    ],
    "Default to a deterministic Haystack retrieval pipeline. Add agent autonomy with smolagents or CrewAI only when bounded tool decisions materially improve the research task.",
  ),
  "worker-b": track(
    choice("langgraph", "Model analysis, evidence checks, revision, and escalation as inspectable nodes."),
    [
      choice("pydantic", "Validate comparison, decision, and NeedsEvidence results."),
      choice("instructor", "Retry structured analysis extraction against typed schemas."),
    ],
    [
      choice("pydantic-ai", "Choose for a smaller typed analysis agent."),
      choice("google-adk", "Choose when analysis workers share an ADK runtime."),
    ],
    "Use LangGraph for multi-step analysis and Pydantic for accepted contracts. Instructor helps extraction; Pydantic AI or ADK should replace, not duplicate, the runtime owner.",
  ),
  "worker-c": track(
    choice("dbos", "Execute approved side effects with durable Python attempts and recovery."),
    [
      choice("pydantic-ai", "Model typed action dependencies and validated results."),
      choice("pycasbin", "Authorize the exact operation from deterministic Python policy facts."),
    ],
    [
      choice("prefect", "Choose for operationally managed cross-system workflows."),
      choice("fastmcp", "Choose when approved actions are exposed through Python MCP servers."),
    ],
    "Use DBOS for durable action code, PyCasbin for authority, and Pydantic AI only for typed agent boundaries. Prefer Prefect for general operations or FastMCP for capability exposure.",
  ),
  "function-tool": track(
    choice("fastmcp", "Expose Python functions as typed MCP capabilities with managed protocol lifecycle."),
    [
      choice("pydantic", "Validate tool arguments, internal types, and returned contracts."),
      choice("langchain-mcp-adapters", "Load approved MCP capabilities into LangGraph."),
    ],
    [
      choice("fastapi", "Choose for an application-owned HTTP tool service."),
      choice("pydantic-ai", "Choose when Pydantic AI owns runtime and MCP client lifecycle."),
    ],
    "Use FastMCP for the server contract and LangChain MCP Adapters for LangGraph consumption. FastAPI is the HTTP alternative; Pydantic AI is conditional on a runtime replacement.",
  ),
  "retrieval-tool": track(
    choice("haystack", "Compose online query routing, hybrid retrieval, filtering, ranking, and evidence output."),
    [
      choice("docling", "Parse complex documents into ingestion-ready structured content."),
      choice("llama-index", "Build document-aware indexes and retrieval workflows."),
      choice("pgvector-python", "Connect the Python retrieval layer to pgvector-backed records."),
    ],
    [
      choice("langchain", "Choose for loader, retriever, and vector-store integration breadth."),
      choice("airflow", "Use only for offline ingestion and re-indexing, never the online retrieval path."),
    ],
    "Use Haystack for online retrieval and Docling for parsing. Add LlamaIndex or LangChain for a specific integration gap; restrict Airflow to offline ingestion and indexing jobs.",
  ),
  "data-source": track(
    choice("sqlalchemy", "Model governed data access, transactions, and connection lifecycle in Python."),
    [
      choice("psycopg", "Use direct PostgreSQL access, async operations, and pooling."),
      choice("trino-python", "Query federated governed sources through Trino from Python."),
    ],
    [choice("pgvector-python", "Add vector types when PostgreSQL also serves governed similarity queries.")],
    "Use SQLAlchemy for the application data layer, Psycopg for direct PostgreSQL control, and the Trino client for federation. Add pgvector-python only to vector-enabled PostgreSQL paths.",
  ),
  "action-tool": track(
    choice("dbos", "Run idempotent Python writes, timers, retries, and reconciliation durably."),
    [
      choice("pydantic", "Validate approved action arguments, results, and postconditions."),
      choice("pycasbin", "Authorize exact action scope from deterministic policy facts."),
    ],
    [
      choice("prefect", "Choose for operational workflow deployment and monitoring."),
      choice("fastmcp", "Choose when the action is published as an approved MCP capability."),
    ],
    "Separate authorization, durable execution, and result validation. Use DBOS for Python durability, Prefect for workflow operations, or FastMCP for the capability boundary.",
  ),
  "policy-guard": track(
    choice("pycasbin", "Evaluate deterministic authorization models at Python service boundaries."),
    [choice("pydantic", "Validate trusted identity, resource, action, and constraint facts before evaluation.")],
    [],
    "Use Pydantic to validate policy facts and PyCasbin to decide. Never delegate authorization to an LLM evaluator.",
  ),
  "output-evaluator": track(
    choice("ragas", "Evaluate RAG and agent results with Python datasets and task-specific metrics."),
    [
      choice("deepeval", "Add reusable unit, integration, and CI evaluation suites."),
      choice("pydantic", "Run deterministic schema checks before semantic judges."),
    ],
    [
      choice("mlflow", "Choose for integrated experiments, datasets, scorers, and production monitoring."),
      choice("dspy", "Choose when modules and prompts are optimized against the evaluator."),
    ],
    "Validate schemas first, then use Ragas or DeepEval for semantic quality. Add MLflow for lifecycle evidence or DSPy only when optimization is an explicit engineering loop.",
  ),
  "human-approval": track(
    choice("langgraph", "Interrupt a Python agent graph and resume with exact reviewed state."),
    [
      choice("dbos", "Persist longer-lived approval waits and durable resume logic in Python."),
      choice("pydantic-ai", "Model typed deferred tool results in a Pydantic AI runtime."),
    ],
    [choice("prefect", "Choose for operationally managed pauses and human workflow interaction.")],
    "Use LangGraph for graph-local review, DBOS for durable Python waits, or Prefect for broader operational workflows. Pydantic AI applies only when it owns the runtime.",
  ),
  "response-publisher": track(
    choice("nats-py", "Publish durable Python outcomes with acknowledgement, replay, and delivery receipts."),
    [
      choice("fastapi", "Stream interactive responses and expose delivery status over HTTP."),
      choice("ag-ui", "Emit backend-neutral agent events to a separate interactive frontend."),
    ],
    [choice("celery", "Choose when delivery already runs through established Celery workers.")],
    "Use nats.py for durable asynchronous publication and FastAPI plus AG-UI for interactive delivery. Celery is appropriate only inside an existing Celery operations model.",
  ),
  "memory-writer": track(
    choice("sqlalchemy", "Persist verified memory records, provenance, policy, and supersession transactionally."),
    [
      choice("psycopg", "Use direct async PostgreSQL writes, pooling, and transaction control."),
      choice("pgvector-python", "Write vector fields and rebuildable similarity indexes."),
    ],
    [choice("mem0", "Choose for an application memory extraction and update layer over governed storage.")],
    "Keep SQLAlchemy or Psycopg as the authoritative write path and pgvector as a projection. Mem0 may prepare memory candidates but must not bypass policy and provenance.",
  ),
  "trace-telemetry": track(
    choice("opentelemetry-python", "Instrument stable traces and metrics in Python with portable context propagation."),
    [
      choice("mlflow", "Correlate AI traces with evaluation, prompts, datasets, and production monitoring."),
      choice("langfuse", "Analyze LLM traces, prompts, scores, and datasets."),
    ],
    [],
    "Instrument at the source with OpenTelemetry Python, noting that its logs signal remains in development. Send telemetry to MLflow or Langfuse according to the analysis workflow.",
  ),
} satisfies Readonly<Record<AgentComponentId, AgentSolutionTrack>>;

function recommendation(
  architecture: AgentSolutionTrack,
  pythonEcosystem: AgentSolutionTrack,
  architectureExceptionReason?: string,
): AgentOpenSourceRecommendation {
  return {
    ...architecture,
    reviewedOn: AGENT_OPEN_SOURCE_REVIEW_DATE,
    pythonEcosystem,
    ...(architectureExceptionReason ? { architectureExceptionReason } : {}),
  };
}

export const agentGroupOpenSourceRecommendations = {
  entry: recommendation(agentGroupArchitectureRecommendations.entry, agentGroupPythonEcosystem.entry, "Edge gateway routing, rate limiting, and TLS termination require infrastructure-level proxy performance that no Python implementation can match at scale."),
  runtime: recommendation(agentGroupArchitectureRecommendations.runtime, agentGroupPythonEcosystem.runtime),
  context: recommendation(agentGroupArchitectureRecommendations.context, agentGroupPythonEcosystem.context),
  models: recommendation(agentGroupArchitectureRecommendations.models, agentGroupPythonEcosystem.models),
  agents: recommendation(agentGroupArchitectureRecommendations.agents, agentGroupPythonEcosystem.agents),
  tools: recommendation(agentGroupArchitectureRecommendations.tools, agentGroupPythonEcosystem.tools, "MCP is a language-neutral protocol specification; no single-language implementation owns the standard."),
  governance: recommendation(agentGroupArchitectureRecommendations.governance, agentGroupPythonEcosystem.governance, "Deterministic policy evaluation requires sub-millisecond latency that Rego's Go runtime delivers; Python bindings exist but do not own the engine."),
  outcome: recommendation(agentGroupArchitectureRecommendations.outcome, agentGroupPythonEcosystem.outcome, "OpenTelemetry is a cross-language observability standard; its Python SDK is first-class but the specification is intentionally language-neutral."),
} satisfies Readonly<Record<AgentGroupId, AgentOpenSourceRecommendation>>;

export const agentComponentOpenSourceRecommendations = {
  "user-application": recommendation(agentComponentArchitectureRecommendations["user-application"], agentComponentPythonEcosystem["user-application"], "The application boundary is a TypeScript frontend; AI SDK provides typed streaming and tool integration that Python cannot serve to the browser."),
  "event-message": recommendation(agentComponentArchitectureRecommendations["event-message"], agentComponentPythonEcosystem["event-message"], "Durable messaging with replay, acknowledgement, and dead-letter requires infrastructure-level broker performance beyond Python's runtime capabilities."),
  "input-gateway": recommendation(agentComponentArchitectureRecommendations["input-gateway"], agentComponentPythonEcosystem["input-gateway"], "Edge proxy routing, TLS termination, and rate limiting require infrastructure-level performance that no Python implementation matches at scale."),
  coordinator: recommendation(agentComponentArchitectureRecommendations.coordinator, agentComponentPythonEcosystem.coordinator),
  "task-scheduler": recommendation(agentComponentArchitectureRecommendations["task-scheduler"], agentComponentPythonEcosystem["task-scheduler"], "Durable cross-service workflow scheduling requires Temporal's Go-based server for persistence, timers, and exactly-once guarantees beyond Python's process boundary."),
  "working-context": recommendation(agentComponentArchitectureRecommendations["working-context"], agentComponentPythonEcosystem["working-context"]),
  "long-term-memory": recommendation(agentComponentArchitectureRecommendations["long-term-memory"], agentComponentPythonEcosystem["long-term-memory"], "PostgreSQL with pgvector provides transactional durability and ACID guarantees at the storage layer that no Python-native store can replace."),
  "skills-instructions": recommendation(agentComponentArchitectureRecommendations["skills-instructions"], agentComponentPythonEcosystem["skills-instructions"]),
  "context-manager": recommendation(agentComponentArchitectureRecommendations["context-manager"], agentComponentPythonEcosystem["context-manager"]),
  "general-model": recommendation(agentComponentArchitectureRecommendations["general-model"], agentComponentPythonEcosystem["general-model"]),
  "private-model": recommendation(agentComponentArchitectureRecommendations["private-model"], agentComponentPythonEcosystem["private-model"]),
  "worker-a": recommendation(agentComponentArchitectureRecommendations["worker-a"], agentComponentPythonEcosystem["worker-a"]),
  "worker-b": recommendation(agentComponentArchitectureRecommendations["worker-b"], agentComponentPythonEcosystem["worker-b"]),
  "worker-c": recommendation(agentComponentArchitectureRecommendations["worker-c"], agentComponentPythonEcosystem["worker-c"], "Write-side execution requires durable workflow guarantees (retries, compensation, reconciliation) that Temporal's server provides beyond Python's process boundary."),
  "function-tool": recommendation(agentComponentArchitectureRecommendations["function-tool"], agentComponentPythonEcosystem["function-tool"]),
  "retrieval-tool": recommendation(agentComponentArchitectureRecommendations["retrieval-tool"], agentComponentPythonEcosystem["retrieval-tool"]),
  "data-source": recommendation(agentComponentArchitectureRecommendations["data-source"], agentComponentPythonEcosystem["data-source"], "Federated query execution across heterogeneous data systems requires Trino's distributed Java engine for performance and connector breadth."),
  "action-tool": recommendation(agentComponentArchitectureRecommendations["action-tool"], agentComponentPythonEcosystem["action-tool"], "Durable write execution requires Temporal's server-level guarantees for idempotency, compensation, and state reconciliation."),
  "policy-guard": recommendation(agentComponentArchitectureRecommendations["policy-guard"], agentComponentPythonEcosystem["policy-guard"], "Sub-millisecond deterministic policy evaluation requires OPA's Go-based Rego engine; Python bindings exist but do not own the runtime."),
  "output-evaluator": recommendation(agentComponentArchitectureRecommendations["output-evaluator"], agentComponentPythonEcosystem["output-evaluator"]),
  "human-approval": recommendation(agentComponentArchitectureRecommendations["human-approval"], agentComponentPythonEcosystem["human-approval"]),
  "response-publisher": recommendation(agentComponentArchitectureRecommendations["response-publisher"], agentComponentPythonEcosystem["response-publisher"], "Durable async delivery with acknowledgement, replay, and dead-letter requires infrastructure-level broker performance beyond Python's runtime capabilities."),
  "memory-writer": recommendation(agentComponentArchitectureRecommendations["memory-writer"], agentComponentPythonEcosystem["memory-writer"], "PostgreSQL provides transactional write guarantees and ACID durability for governed memory records that no Python-native store can replace."),
  "trace-telemetry": recommendation(agentComponentArchitectureRecommendations["trace-telemetry"], agentComponentPythonEcosystem["trace-telemetry"], "OpenTelemetry is a cross-language observability standard; its Python SDK is first-class but the specification is intentionally language-neutral."),
} satisfies Readonly<Record<AgentComponentId, AgentOpenSourceRecommendation>>;

export function getAgentGroupOpenSourceRecommendation(
  groupId: AgentGroupId,
): AgentOpenSourceRecommendation {
  return agentGroupOpenSourceRecommendations[groupId];
}

export function getAgentComponentOpenSourceRecommendation(
  componentId: AgentComponentId,
): AgentOpenSourceRecommendation {
  return agentComponentOpenSourceRecommendations[componentId];
}
